image: atlassian/default-image:2
pipelines:
  default:
    - step:    
        caches:
          - git-modules
        script:            
          - apt-get update; apt-get install -y jq unzip lib32ncurses5 lib32z1 lib32stdc++6 tree
          - git submodule update --recursive --init
          - source bitbucket-pipelines-dependencies.sh
          - ./build_test
          - cd ./build/test
          - ../../build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir SonarQube-output make clean all
          - cd -
          - export SONAR_SCANNER_OPTS="-Xmx1024m"
          - ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.login=492dba2b1a7da82eaea36308ce177f6033626bca -Dsonar.cfamily.build-wrapper-output=build/test/SonarQube-output
                 
definitions:
  caches:
    git-modules: .git/modules

